title: Vero Agnolutto
description: > 
  <div style="display: flex; width: 100%;">
    <img src="/images/vero.png?raw=true" style="width: 80%; object-fit: cover;">
  </div>
  <div style="text-align: justify; margin-top: 24px;">
  <em>AI enthusiast · engineer · dogs lover</em>
  <br>
  📍 Barcelona, Spain
  <div style="margin-top: 24px;">
  Hi, I’m Vero 👋
  <div style="margin-top: 6px;">
  AI Engineer with roots in Building Engineering.
  <div style="margin-top: 12px;">
  <em>
  I build scalable ML and AI systems that turn complex data into practical solutions, combining engineering rigor with creative thinking to deliver positive impact.</em>
  </div>
  <div style="display: flex; gap: 20px; margin-top: 24px;">
    <a href="mailto:vero.agnolutto@gmail.com">
      <img src="/images/logos/email.png" height="20" width="20" alt="">
    </a>
    <a href="https://www.linkedin.com/in/veroagnolutto/" target="_blank">
      <img src="/images/logos/linkedin.png" height="20" width="20" alt="">
    </a>
    <a href="https://github.com/cucu-o0" target="_blank">
      <img src="/images/logos/github.png" height="20" width="20" alt="">
    </a>
  </div>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PWZGCYFDSY
