title: Vero Agnolutto
logo: "/images/vero.png?raw=true" # your photo (or logo) here
description: > 
  <div style="text-align: justify;">
  AI enthusiast · building engineer · dogs lover
  <br>
  <h1>Hello there! 👋</h1>

  Hi! I'm Vero 👋 — an Italian AI Engineer with a Building Engineering background.
  <br><br>
  <em>I love to design ML and Generative AI solutions to solve real-world data challenges, building automation that makes processes smarter and faster!</em>

  <h2>About me ✨</h2>

  🎓 Research Engineer <a href="https://www.starlab.es/">@Starlab</a><br>
  🤖 AI/ML Engineer <a href="https://assistdigital.com/tech/botshelf">@Assist Digital</a><br>
  ⚕️ Data Scientist <a href="https://en.trialing.org/">@Trialing</a><br>
  🤖 Data Enthusiast <a href="https://www.ironhack.com/">@Ironhack</a><br>
  🏗️ MSc Building Engineering <a href="https://www.unitn.it/en">@Università degli Studi di Trento</a><br>
  📍 Barcelona, Spain

  <h2>Areas of Interest 🧠</h2>

  💙 Passionate about <code>Data · ML · AI</code><br>
  👀 Exploring <code>MLOps · LLMOps · AI Agents</code><br>
  🌱 Focus on <code>AI for Good · Innovation</code>

  </div>
  <div style="display: flex; gap: 20px; margin-top: 12px;">
  <div>
    <img src="/images/logos/linkedin.png" height="16" width="16">
    <a href="https://www.linkedin.com/in/veroagnolutto/">LinkedIn</a> 
  </div>
  <div>
    <img src="/images/logos/github.png" height="16" width="16">
    <a href="https://github.com/cucu-o0">X</a>
  </div>
  </div>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PWZGCYFDSY
