title: Vero Agnolutto
description: > 
  <div style="text-align: left;">
    <img src="/images/vero.png?raw=true" style="width: 90%;">
  </div>
  <div style="text-align: justify;">
  <em>AI enthusiast · engineer · dogs lover</em>
  <br>
  📍 Barcelona, Spain
  <div style="margin-top: 12px;">
  Hello there! 
  <br>
  I'm Vero 👋 — an Italian AI Engineer with a Building Engineering background.
  <br>
  <em>I love to design ML and Generative AI solutions to solve real-world data challenges, building automation that makes processes smarter and faster!</em>
  </div>
  <div style="display: flex; gap: 10px; margin-top: 6px;">
  <div>
  <a href="mailto:vero.agnolutto@gmail.com">
    <img src="/images/logos/email.png" height="16" width="16">
    Email
  </a>
  </div>  
  <div>
    <a href="https://www.linkedin.com/in/veroagnolutto/" target="_blank">
      <img src="/images/logos/linkedin.png" height="16" width="16">
      LinkedIn
    </a>
  </div>
  <div>
    <a href="https://github.com/cucu-o0" target="_blank">
      <img src="/images/logos/github.png" height="16" width="16">
      GitHub
    </a>
  </div>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PWZGCYFDSY
